version: "3.9"

services:
  nuxt:
    container_name: onof-storefront

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "80:3000"

    environment:
      NODE_ENV: production

    volumes:
      - .:/app
      - /app/node_modules

    restart: unless-stopped
